{{- if .Values.frontend.enabled }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-frontend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "http-metrics"
spec:
  replicas: {{ .Values.frontend.replicas.app }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
      # serviceAccountName: vault-auth
      imagePullSecrets:
        - name: regcred
      containers:
        - name: {{ .Release.Name }}-front
          image: {{ pluck $.Values.global.env .Values.frontend.image | first | default .Values.frontend.image._default | quote }}
          resources:
          {{- with .Values.frontend.resources }}
            limits:
              memory: {{ pluck $.Values.global.env .limits.memory | first | default .limits.memory._default | quote }}
              cpu: {{ pluck $.Values.global.env .limits.cpu | first | default .limits.cpu._default | quote }}
            requests:
              memory: {{ pluck $.Values.global.env .requests.memory | first | default .requests.memory._default | quote }}
              cpu: {{ pluck $.Values.global.env .requests.cpu | first | default .requests.cpu._default | quote }}
          {{- end }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.frontend.docker.targetPort }}
          env:
{{- include "app_env" . | indent 10 }}
          # volumeMounts:
          #   - name: smweb-logs
          #     mountPath: /usr/local/sm-web-server/log
          # readinessProbe:
          #   httpGet:
          #     path: /appversion
          #     port: {{ .Values.frontend.docker.port }}
          #     scheme: HTTP
          #   initialDelaySeconds: 60
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /appversion
          #     port: {{ .Values.frontend.docker.port }}
          #     scheme: HTTP
          #   initialDelaySeconds: 100
          #   periodSeconds: 100
      # volumes:
      #   - name: smweb-logs
      #     emptyDir: { }
      #   - name: config
      #     configMap:
      #       name: {{ .Release.Name }}-promtail-configmap
      restartPolicy: Always
      {{- if .Values.frontend.nodeSelector.enabled }}
      nodeSelector:
        app: {{ .Values.frontend.nodeSelector.app }}
      {{- end }}
---
{{- end }}
