{{- if .Values.frontend.enabled }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-frontend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "http-metrics"
spec:
  replicas: {{ .Values.frontend.replicas.app }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      {{- if eq .Values.frontend.image.pullPolicy "Always" }}
      annotations:
        releaseTime: {{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC"| quote }}
      {{- end }}
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
      # serviceAccountName: vault-auth
      imagePullSecrets:
        - name: regcred
      containers:
        - name: {{ .Release.Name }}-front
          image: {{ pluck $.Values.global.env .Values.frontend.image | first | default .Values.frontend.image._default | quote }}
          resources:
          {{- with .Values.frontend.resources }}
            limits:
              memory: {{ pluck $.Values.global.env .limits.memory | first | default .limits.memory._default | quote }}
              cpu: {{ pluck $.Values.global.env .limits.cpu | first | default .limits.cpu._default | quote }}
            requests:
              memory: {{ pluck $.Values.global.env .requests.memory | first | default .requests.memory._default | quote }}
              cpu: {{ pluck $.Values.global.env .requests.cpu | first | default .requests.cpu._default | quote }}
          {{- end }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.docker.targetPort }}
          env:
{{- include "frontend_env" . | indent 10 }}
          # volumeMounts:
          #   - name: smweb-logs
          #     mountPath: /usr/local/sm-web-server/log
          {{- if .Values.frontend.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.readinessProbe.path }}
              port: {{ .Values.frontend.docker.targetPort }}
              scheme: HTTP
            {{- with .Values.frontend.readinessProbe.params }}
            {{ . | toYaml | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- if .Values.frontend.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.livenessProbe.path }}
              port: {{ .Values.frontend.docker.targetPort }}
              scheme: HTTP
            {{- with .Values.frontend.livenessProbe.params }}
            {{ . | toYaml | nindent 12 }}
            {{- end }}
          {{- end }}
      # volumes:
      #   - name: smweb-logs
      #     emptyDir: { }
      #   - name: config
      #     configMap:
      #       name: {{ .Release.Name }}-promtail-configmap
      restartPolicy: Always
      {{- if .Values.frontend.nodeSelector.enabled }}
      nodeSelector:
      {{- pluck $.Values.global.env .Values.frontend.nodeSelector.labels | first | default .Values.frontend.nodeSelector.labels._default | toYaml | nindent 8 }}
      {{- end }}
---
{{- end }}
