{{- if .Values.frontend.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-frontend-svc
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.docker.port }}
      targetPort: {{ .Values.frontend.docker.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-frontend
---
{{- end }}
