apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-rds-svc
  name: db-svc
spec:
  externalName: {{ .Values.rds.endpoint }}
  selector:
    app: {{ .Release.Name }}-rds-svc
  type: ExternalName
status:
  loadBalancer: {}
