/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as testNftFlatSol from "./TestNFT_flat.sol";
export type { testNftFlatSol };
import type * as testTokenOwnedFlatSol from "./TestTokenOwned_flat.sol";
export type { testTokenOwnedFlatSol };
import type * as testTokenFlatSol from "./TestToken_flat.sol";
export type { testTokenFlatSol };
export type { TestNFT } from "./TestNFT";
export type { TestToken } from "./TestToken";
