{{- if .Values.ethBytecodeDb.enabled }}
{{- if .Values.ethBytecodeDb.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: internal-and-public
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    nginx.ingress.kubernetes.io/client-max-body-size: "500M"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "15m"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "15m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "15m"
    cert-manager.io/cluster-issuer: "zerossl-prod"
    {{- range .Values.ethBytecodeDb.ingress.annotations }}
    {{ . }}
    {{- end}}
  name: {{ .Release.Name }}-eth-bytecode-db-ingress
spec:
  rules:
    - host: {{ pluck $.Values.global.env .Values.ethBytecodeDb.ingress.host | first | default .Values.ethBytecodeDb.ingress.host._default | quote }}
      http:
        paths:
          # - path: "/metrics"
          #   pathType: Exact
          #   backend:
          #     service:
          #       name: ethBytecodeDb-svc
          #       port:
          #         number: {{ .Values.ethBytecodeDb.docker.metricsPort }}
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: eth-bytecode-db-svc
                port:
                  number: {{ .Values.ethBytecodeDb.docker.port }}
  {{- if .Values.ethBytecodeDb.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ pluck $.Values.global.env .Values.ethBytecodeDb.ingress.host | first | default .Values.ethBytecodeDb.ingress.host._default | quote }}
      {{- if .Values.ethBytecodeDb.ingress.tls.createSecret }}
      secretName: {{ .Release.Name }}-eth-bytecode-db-tls
      {{- end }}
  {{- end }}
{{- end }}
{{- end }}
