{{- if .Values.ethBytecodeDb.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: eth-bytecode-db-svc
  labels:
    app: {{ .Release.Name }}-eth-bytecode-db
spec:
  type: {{ .Values.ethBytecodeDb.service.type}}
  ports:
    - port: {{ .Values.ethBytecodeDb.docker.port }}
      targetPort: {{ .Values.ethBytecodeDb.docker.targetPort }}
      protocol: TCP
      name: web
    - port: {{ .Values.ethBytecodeDb.docker.metricsPort }}
      targetPort: {{ .Values.ethBytecodeDb.docker.metricsPort }}
      protocol: TCP
      name: http-metrics
  selector:
    app: {{ .Release.Name }}-eth-bytecode-db
{{- end }}
---
