{{- if .Values.node.enabled }}
{{- if .Values.node.files.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-cm
data:
  {{- range $key, $value := .Values.node.files.list }}
  {{ $key }}: {{ toYaml $value | indent 2 }}
  {{- end }}
  # genesis.json: {{ toYaml .Values.node.files.genesis | indent 2 }}
  # init.sh: {{ toYaml .Values.node.files.init | indent 2 }}
  # password.txt: ""
{{- end }}
{{- end }}
