{{- if .Values.node.enabled }}
{{- if .Values.node.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: internal-and-public
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    nginx.ingress.kubernetes.io/client-max-body-size: "500M"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "15m"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "15m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "15m"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    {{- if .Values.node.ingress.tls.enabled }}
    cert-manager.io/cluster-issuer: "letsencrypt-cluster"
    {{- end }}
  name: {{ .Release.Name }}-node-ingress
spec:
  rules:
    - host: {{ .Values.node.ingress.host }}
      http:
        paths:
          - path: "/http(/|$)(.*)"
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-node-svc
                port:
                  number: {{ .Values.node.portHttp }}
          - path: /ws(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-node-svc
                port:
                  number: {{ .Values.node.portWs }}
          # - path: /discovery(/|$)(.*)
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: {{ .Release.Name }}-node-svc
          #       port:
          #         number: {{ .Values.node.portDiscovery }}
  {{- if .Values.node.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.node.ingress.host }}
      secretName: {{ .Release.Name }}-node-tls
  {{- end }}
{{- end }}
{{- end }}
