{{- if .Values.visualizer.enabled }}
{{- if .Values.visualizer.hpa.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-visualizer
spec:
  maxReplicas: {{ .Values.visualizer.hpa.maxReplicas }}
  minReplicas: {{ .Values.visualizer.hpa.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-visualizer
  targetCPUUtilizationPercentage: {{ .Values.visualizer.hpa.cpuTarget }}
{{- end }}
{{- end }}
