{
 "title": "Blockscout indexers",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  { "title": "Ecto", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ecto DB query quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(ecto_db_query_duration_microseconds_bucket{result=\"ok\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "ok - 99"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(ecto_db_query_duration_microseconds_bucket{result=\"fail\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "fail - 99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(ecto_db_query_duration_microseconds_bucket{result=\"ok\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "ok - 95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(ecto_db_query_duration_microseconds_bucket{result=\"ok\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "ok - 50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(ecto_db_query_duration_microseconds_bucket{result=\"fail\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "fail - 95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(ecto_db_query_duration_microseconds_bucket{result=\"fail\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "fail - 50"
    }
   ]
  },
  {
   "title": "Ecto query quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(ecto_query_duration_microseconds_bucket{result=\"ok\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "ok - 99"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(ecto_query_duration_microseconds_bucket{result=\"fail\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "fail - 99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(ecto_query_duration_microseconds_bucket{result=\"ok\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "ok - 95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(ecto_query_duration_microseconds_bucket{result=\"ok\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "ok - 50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(ecto_query_duration_microseconds_bucket{result=\"fail\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "fail - 95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(ecto_query_duration_microseconds_bucket{result=\"fail\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "fail - 50"
    }
   ]
  },
  {
   "title": "Ecto queue quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(ecto_queue_duration_microseconds_bucket{result=\"ok\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "ok - 99"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(ecto_queue_duration_microseconds_bucket{result=\"fail\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "fail - 99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(ecto_queue_duration_microseconds_bucket{result=\"ok\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "ok - 95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(ecto_queue_duration_microseconds_bucket{result=\"ok\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "ok - 50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(ecto_queue_duration_microseconds_bucket{result=\"fail\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "fail - 95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(ecto_queue_duration_microseconds_bucket{result=\"fail\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "fail - 50"
    }
   ]
  },
  { "title": "Indexers data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Block import quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(block_import_duration_microseconds_bucket{fetcher=\"Elixir.Indexer.Block.Catchup.Fetcher\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "Catchup - 99"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(block_import_duration_microseconds_bucket{fetcher=\"Elixir.Indexer.Block.Realtime.Fetcher\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "Realtime - 99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(block_import_duration_microseconds_bucket{fetcher=\"Elixir.Indexer.Block.Catchup.Fetcher\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "Catchup - 95"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(block_import_duration_microseconds_bucket{fetcher=\"Elixir.Indexer.Block.Realtime.Fetcher\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "Realtime - 95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(block_import_duration_microseconds_bucket{fetcher=\"Elixir.Indexer.Block.Catchup.Fetcher\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "Catchup - 50"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(block_import_duration_microseconds_bucket{fetcher=\"Elixir.Indexer.Block.Realtime.Fetcher\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "Realtime - 50"
    }
   ]
  },
  {
   "title": "Block batch fetch quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(block_batch_fetch_request_duration_microseconds_bucket{fetcher=\"Elixir.Indexer.Block.Catchup.Fetcher\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "Catchup - 99"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(block_batch_fetch_request_duration_microseconds_bucket{fetcher=\"Elixir.Indexer.Block.Realtime.Fetcher\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "Realtime - 99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(block_batch_fetch_request_duration_microseconds_bucket{fetcher=\"Elixir.Indexer.Block.Catchup.Fetcher\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "Catchup - 95"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(block_batch_fetch_request_duration_microseconds_bucket{fetcher=\"Elixir.Indexer.Block.Realtime.Fetcher\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "Realtime - 95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(block_batch_fetch_request_duration_microseconds_bucket{fetcher=\"Elixir.Indexer.Block.Catchup.Fetcher\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "Catchup - 50"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(block_batch_fetch_request_duration_microseconds_bucket{fetcher=\"Elixir.Indexer.Block.Realtime.Fetcher\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "Realtime - 50"
    }
   ]
  },
  {
   "title": "Pending blocks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "pending_block_operations_count{namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Block full processing fetch quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(block_full_processing_duration_microseconds_bucket{fetcher=\"Elixir.Indexer.Block.Catchup.Fetcher\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "Catchup - 99"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(block_full_processing_duration_microseconds_bucket{fetcher=\"Elixir.Indexer.Block.Realtime.Fetcher\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "Realtime - 99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(block_full_processing_duration_microseconds_bucket{fetcher=\"Elixir.Indexer.Block.Catchup.Fetcher\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "Catchup - 95"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(block_full_processing_duration_microseconds_bucket{fetcher=\"Elixir.Indexer.Block.Realtime.Fetcher\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "Realtime - 95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(block_full_processing_duration_microseconds_bucket{fetcher=\"Elixir.Indexer.Block.Catchup.Fetcher\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "Catchup - 50"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(block_full_processing_duration_microseconds_bucket{fetcher=\"Elixir.Indexer.Block.Realtime.Fetcher\", namespace=\"$namespace\"}[$__rate_interval])) by (le)) * 1e-3",
     "legendFormat": "Realtime - 50"
    }
   ]
  },
  {
   "title": "Import errors count (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "rate(import_errors_count{namespace=\"$namespace\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Missing blocks count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "missing_block_count{namespace=\"$namespace\"}"
    }
   ]
  }
 ]
}