{
 "title": "Verifier",
 "time": { "from": "2022-09-09T12:11:16.469Z", "to": "2022-09-09T13:56:06.608Z" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Geth logs",
     "type": "logs",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", container=\"geth\"}"
      }
     ]
    },
    {
     "title": "Blockscout logs",
     "type": "logs",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", container=\"node\"}"
      }
     ]
    },
    {
     "title": "Verifier logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", container=\"smart-contract-verifier\"}"
      }
     ]
    }
   ]
  },
  { "title": "Verifier metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Verification pass/fail",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smart_contract_verifier_verify_contract{namespace=\"$namespace\"}",
     "legendFormat": "{{exported_endpoint}} - {{status}}"
    },
    {
     "legendFormat": "{{exported_endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Request counters",
   "type": "stat",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smart_contract_verifier_http_requests_total{namespace=\"$namespace\"}",
     "legendFormat": "{{exported_endpoint}} - {{method}} - {{status}}"
    },
    {
     "legendFormat": "{{exported_endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Compile time quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(smart_contract_verifier_compile_time_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "compile - 99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(smart_contract_verifier_compile_time_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "compile - 95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(smart_contract_verifier_compile_time_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "compile - 50"
    }
   ]
  },
  {
   "title": "Compiler fetch time quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(smart_contract_verifier_compiler_fetch_time_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "fetch - 99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(smart_contract_verifier_compiler_fetch_time_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "fetch - 95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(smart_contract_verifier_compiler_fetch_time_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "fetch - 50"
    }
   ]
  },
  {
   "title": "Requests quaantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(smart_contract_verifier_http_requests_duration_seconds_bucket{namespace=\"$namespace\", exported_endpoint=\"/api/v1/solidity/verify/multiple-files\"}[$__rate_interval])) by (le))",
     "legendFormat": "/api/v1/solidity/verify/multiple-files - 99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(smart_contract_verifier_http_requests_duration_seconds_bucket{namespace=\"$namespace\",exported_endpoint=\"/api/v1/solidity/verify/multiple-files\"}[$__rate_interval])) by (le))",
     "legendFormat": "/api/v1/solidity/verify/multiple-files - 95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(smart_contract_verifier_http_requests_duration_seconds_bucket{namespace=\"$namespace\",exported_endpoint=\"/api/v1/solidity/verify/multiple-files\"}[$__rate_interval])) by (le))",
     "legendFormat": "/api/v1/solidity/verify/multiple-files - 50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(smart_contract_verifier_http_requests_duration_seconds_bucket{namespace=\"$namespace\",exported_endpoint=\"/api/v1/solidity/verify/standard-json\"}[$__rate_interval])) by (le))",
     "legendFormat": "/api/v1/solidity/verify/standard-json - 99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(smart_contract_verifier_http_requests_duration_seconds_bucket{namespace=\"$namespace\",exported_endpoint=\"/api/v1/solidity/verify/standard-json\"}[$__rate_interval])) by (le))",
     "legendFormat": "/api/v1/solidity/verify/standard-json - 95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(smart_contract_verifier_http_requests_duration_seconds_bucket{namespace=\"$namespace\",exported_endpoint=\"/api/v1/solidity/verify/standard-json\"}[$__rate_interval])) by (le))",
     "legendFormat": "/api/v1/solidity/verify/standard-json - 50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(smart_contract_verifier_http_requests_duration_seconds_bucket{namespace=\"$namespace\",exported_endpoint=\"/api/v1/solidity/versions\"}[$__rate_interval])) by (le))",
     "legendFormat": "/api/v1/solidity/versions - 99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(smart_contract_verifier_http_requests_duration_seconds_bucket{namespace=\"$namespace\",exported_endpoint=\"/api/v1/solidity/versions\"}[$__rate_interval])) by (le))",
     "legendFormat": "/api/v1/solidity/versions - 95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(smart_contract_verifier_http_requests_duration_seconds_bucket{namespace=\"$namespace\",exported_endpoint=\"/api/v1/solidity/versions\"}[$__rate_interval])) by (le))",
     "legendFormat": "/api/v1/solidity/versions - 50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(smart_contract_verifier_http_requests_duration_seconds_bucket{namespace=\"$namespace\",exported_endpoint=\"/health\"}[$__rate_interval])) by (le))",
     "legendFormat": "/health - 99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(smart_contract_verifier_http_requests_duration_seconds_bucket{namespace=\"$namespace\",exported_endpoint=\"/health\"}[$__rate_interval])) by (le))",
     "legendFormat": "/health - 95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(smart_contract_verifier_http_requests_duration_seconds_bucket{namespace=\"$namespace\",exported_endpoint=\"/health\"}[$__rate_interval])) by (le))",
     "legendFormat": "/health - 50"
    }
   ]
  },
  {
   "title": "Cache hit/total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "smart_contract_verifier_download_cache_hits{namespace=\"$namespace\"}",
     "legendFormat": "cache hits - {{instance}}"
    },
    {
     "expr": "smart_contract_verifier_download_cache_total{namespace=\"$namespace\"}",
     "legendFormat": "cache total - {{instance}}"
    }
   ]
  }
 ]
}