{{- if .Values.allowance.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-allowance-svc
spec:
  type: {{ .Values.allowance.service.type}}
  ports:
    - port: {{ .Values.allowance.docker.port }}
      targetPort: {{ .Values.allowance.docker.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-allowance
---
{{- end }}
