{{- if .Values.postgres.enabled }}
{{- if .Values.postgres.persistence }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgres-pv-claim
spec:
  {{- if .Values.postgres.storageClass }}
  {{- with .Values.postgres.storageClass }}
  storageClassName: {{ . | toYaml | nindent 6 }}
  {{- end }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  {{- if hasKey .Values.postgres.existingPV $.Values.global.env }}
  volumeName: {{ pluck $.Values.global.env .Values.postgres.existingPV | first | default .Values.postgres.existingPV._default | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage | quote }}
---
{{- end }}

{{- end }}
