{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: {{ .Release.Name }}-postgres
spec:
  type: {{ .Values.postgres.service.type}}
  ports:
    - port: {{ .Values.postgres.port }}
  selector:
    app: {{ .Release.Name }}-postgres
{{- end }}
