{{- if .Values.blockscout.enabled }}
{{- if .Values.blockscout.rds.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-rds-svc
  name: db-svc
spec:
  externalName: {{ pluck $.Values.global.env .Values.blockscout.rds.endpoint | first | default .Values.blockscout.rds.endpoint._default | quote }}
  selector:
    app: {{ .Release.Name }}-rds-svc
  type: ExternalName
status:
  loadBalancer: {}
{{- end }}
{{- end }}
