{{- if .Values.blockscout.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-blockscout-svc
spec:
  endpoints:
  - scrapeTimeout: 10s
    port: http
    path: /metrics
  selector:
    matchLabels:
      app: {{ .Release.Name }}-blockscout-svc
{{- end }}
