{{- if .Values.stats.enabled }}
{{- if .Values.stats.rds.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-stats-rds-svc
  name: db-stats-svc
spec:
  externalName: {{ pluck $.Values.global.env .Values.stats.rds.endpoint | first | default .Values.stats.rds.endpoint._default | quote }}
  selector:
    app: {{ .Release.Name }}-stats-rds-svc
  type: ExternalName
status:
  loadBalancer: {}
{{- end }}
{{- end }}
