{{- if .Values.stats.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-stats
spec:
  endpoints:
  - scrapeTimeout: 10s
    port: http-metrics
    path: /metrics
  selector:
    matchLabels:
      app: {{ .Release.Name }}-stats
{{- end }}
