/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20 } from "./ERC20";
export type { IERC20 } from "./IERC20";
export type { IERC20Metadata } from "./IERC20Metadata";
export type { Ownable } from "./Ownable";
export type { TestToken } from "./TestToken";
