blockscout:
    environment:
        ACCOUNT_USERNAME:
            _default: ENC[AES256_GCM,data:n9Wc7xjBFdWHJNaKBwpVVykz3FbBtqicKdf6yD/kMLKuts/0Rv8vfQ20gSahIvSbbno=,iv:FRyRAwelWF1PHqbIJX09MH+VVqW53luYraLYq/A21j4=,tag:YUejqoXCZjWNUhRZ9emd+g==,type:str]
        ACCOUNT_PASSWORD:
            _default: ENC[AES256_GCM,data:JVEI0zxaV0pNe74DDB75gt0=,iv:v05W/HN2vzF85yuYWjJYDm1IWgYd2UdeMEnXgfVbYfo=,tag:+8afW2VG1z8ke78vM4N+Lw==,type:str]
        MAILSLURP_API_KEY:
            _default: ENC[AES256_GCM,data:8RffJ77fEUMK41bBeFbJDaqvvbVgtoSKbVItKkWl3TaV7V605qQLdRPPo9pc4wpWDYtMDPZ7du9rjjr8R16jpg==,iv:voau83nNEXZN65F/ZEno0TOEToCEHBNt7tiAFigIqlI=,tag:Q9Ozhcnz32aNmYiVg3c6Rw==,type:str]
        MAILSLURP_EMAIL_ID:
            _default: ENC[AES256_GCM,data:xTJjX9TJvcWNHGtlIPrsyI1FrQfTx5mz/ImA2PQjPWzo59q5,iv:mhu9H73Dg6q8aYhPU7+ly5HGJddUmLi3AuoAWePbvtc=,tag:wyi0Y7FH8zTwjtft5nAsLg==,type:str]
        ACCOUNT_AUTH0_DOMAIN:
            _default: ENC[AES256_GCM,data:dhZF85GiypKiyY3TBIuZfNhtTk+qMU0Kz9k=,iv:kEfANVJvafgxvjR7tYQc1S5JUJVfULPJJCKovBeBGgI=,tag:3Ct3Fe3Z3ptMTEnJyr7Ikg==,type:str]
        ACCOUNT_AUTH0_CLIENT_ID:
            _default: ENC[AES256_GCM,data:pSld6tuuYhncmzE5gGc3SADX/tdAEb5LEZnSL1mpnEc=,iv:DzM79h6dfNfgIGfyOR619Xds7tMFeyqg/lB44mhJV3Y=,tag:o7jJy6muYkcPFF7XbdtpYA==,type:str]
        ACCOUNT_AUTH0_CLIENT_SECRET:
            _default: ENC[AES256_GCM,data:UuREfWlWDbWBes9xhENm06vuySG5GjN3yE9AtYGy/kMZXPk33wZbbuNWgxX8Q8IOJx8DvmNXUE5/h1nh6vVPnA==,iv:BDmJCwipEkVZ/WM5j8F5LyUAtEtcpXzgkIzeyKZFvSU=,tag:2aUN9626VX6zgpfzd1qKBw==,type:str]
        ACCOUNT_AUTH0_CALLBACK_URL:
            _default: ENC[AES256_GCM,data:plsc90jh5ggPoyejhUsAWUA4XdiScMD9cSXgQU/j1xu005KHQudUAVEoWXIhb444gvufy5IQA5V1Eu5kagWk6w2BFNKGMkLw,iv:9QMEHCQ54s8/bFICXU05kZWUnIgV1KCzYpjdaG4KNFA=,tag:IQgfWKdffIRnb3/3EFSb7g==,type:str]
        ACCOUNT_AUTH0_LOGOUT_RETURN_URL:
            _default: ENC[AES256_GCM,data:jS7AbTVuIjk89s00wO5QzN6R+G61G4YQd+KfyVgXLTT7192fZU89yPYaJkVJZvxJzDp6xcN7viSHWLYmgTl5nQ==,iv:shI+ibsp/fHHPlZ5L9JRt6qcGIHKiSPQKIeLzbydfOU=,tag:XDtNLFOowaMjBvfR6OJoVA==,type:str]
        ACCOUNT_AUTH0_LOGOUT_URL:
            _default: ENC[AES256_GCM,data:FpIq9cXpqmBXpmVBj9seZB7vpbuJ5q+Iz5ChgL7+g6dgosufrO93tl4wsQk=,iv:DM4qKBrIyeQOmMMSPhEKiW26kEL0yHVA58na8tXZX0o=,tag:kTEy1KUinGUfe/cq1UARQA==,type:str]
        ACCOUNT_SENDGRID_API_KEY:
            _default: ENC[AES256_GCM,data:bThnhRnrnTvQ+4f/p7tH0j3F7IoHx9/9JUfOEnU+xkuoXTJvDOlrsj1PVgj0fQeYrE9cDv2lCO3esad3VajzA96Xbqav,iv:qDAg8am06D9LFcryySEa/1P82lyvOSC9BeTOtzpUEas=,tag:flUEez9YvQdewKJIYJycEA==,type:str]
        ACCOUNT_SENDGRID_SENDER:
            _default: ENC[AES256_GCM,data:jnaN7XRQnjAJ1oOcswIBiBE8ZWqT4Q==,iv:WJHNTmwzE5FgZcu8hqoSiwWjYlr9fARW0nZY+ci/2eI=,tag:Ks+yhmJCA9hscHUYk3e+9g==,type:str]
        ACCOUNT_SENDGRID_TEMPLATE:
            _default: ENC[AES256_GCM,data:26r5ti5xVwlf5Fr4vtNxmk1mYxg5DjcI9IO12WSI8dIlcA==,iv:hc9YA3Y0Lney3/+fpTeVEX0GuuxdhNJFpd4B30mGHOc=,tag:8k/GfGHzdylAwTs0QWFXQg==,type:str]
        ACCOUNT_PUBLIC_TAGS_AIRTABLE_URL:
            _default: ENC[AES256_GCM,data:b/+BmS5vj6rtKGFHdODTiMGAU05WG0MTT9rQtFXLkKPL+zv4ehKRB9vDa/FwlTNldkOFooIdDfys2H4fuKw=,iv:PvMXWccd47dZNdSWMnrSZceSTcgRNLelCB3F/UjcSkU=,tag:iwwRZrEUqyR5B84iUh5vkQ==,type:str]
        ACCOUNT_PUBLIC_TAGS_AIRTABLE_API_KEY:
            _default: ENC[AES256_GCM,data:aekJKcQxlb0xsS9MVoJ4+rI=,iv:RJQQsxoSfzSSL949za2BO6r/qta/jcdcjncSWKhLTr0=,tag:5YtSW7877zoyUyjpWng+Dw==,type:str]
        ACCOUNT_CLOAK_KEY:
            _default: ENC[AES256_GCM,data:kmbDlujc+JB7VNsMEwnlTXIC9zuN0smaYKYvmfMCVk484qe+1fbmhgeW0rM=,iv:b/sPf2xfGJgMgDL4UIF7K5iFuKJD3XfLIUI86E/Ltno=,tag:/lJj8VKQlYeDpsGYbqkVAg==,type:str]
        SECRET_KEY_BASE:
            _default: ENC[AES256_GCM,data:pojKRWQIlKeiqpGxEPe0p3n2VGe5zgBMvowU5jZzNofnoRXtgXPKdFpsWNPVzYtxFUOliNt5YmuIoQfobE1eaWqk2HVmQkvluSsJZuodkipFvc5bo5P1wzJGeOJ/hd+7dxYsdjKhqpWU1+OETpEy9VTxNCU8DzaIWPCddrS4Kt4=,iv:U7eTYtpNFcqXDbvGHX+P2WnQWhzBKMO3xZBiZVLXN4w=,tag:j0nNFBZhOBbI87bA8XjizQ==,type:str]
        DATABASE_URL:
            _default: ENC[AES256_GCM,data:9MKvBnelyJTdRBUuwL5oqmyBB4fphgYnQdKTzdL12gpNbDBdZTDVTeU/RHyL2rcuaHKLN6yEG10N6MZ4dEXAciQ=,iv:Uj3KA7kyRETJmW3LK41ziJsIpuq50PcggH7wDDOCSIw=,tag:gUswuDk7AefQerkqoRpKPg==,type:str]
        ACCOUNT_DATABASE_URL:
            _default: ENC[AES256_GCM,data:b6ZuCyEkINzvv2osvlQP8iTh4fwoivVCPOEKy5QRHs0cbVW4f3bp//HATPuAhD2T3MA/OSyqv5Xh6DpRjKPBV68=,iv:Yon9UJXtBmAXUX/G7BSKsbCT64eqM0nJ3AiMvgTxeRM=,tag:jWb4JgTI4b/bEbhgTuPBXg==,type:str]
        ACCOUNT_REDIS_URL:
            _default: ENC[AES256_GCM,data:a+lfkUrRstKt8sc/SqlDqr2d0iub9hy3ttzLklGirIuakYay5druY5Yma8WA5fy/E/LgsP0xTIbE2Xvd23L33tpOWeh1KuLsiM0W+D6NIInf,iv:s3mMrzKfw0OMsYScu1xaqfK6uTgR/Pp57FR+nvuK1lA=,tag:nkk22fDDQEr7UIKfCxTtHA==,type:str]
        ETHEREUM_JSONRPC_TRACE_URL:
            _default: ENC[AES256_GCM,data:WE/3lqciAdzCtJa9+mmscccn1l7WACx0Hw==,iv:+NTsqnzegDVtj6fOFboBeM0zkJgLWmeV+7IcXPFDChQ=,tag:T0wbtz0uJSK2UbPcR4aR4w==,type:str]
        ETHEREUM_JSONRPC_HTTP_URL:
            _default: ENC[AES256_GCM,data:JAPSPrqPW6cvLxZitWk1MjXfzwVsYqehBw==,iv:lxoIh4jsLN19zQv/+CNz7rqCXrW054S+zk6XN+Nr22w=,tag:V6IRiLNsh+nSFuvRoEZYww==,type:str]
        ETHEREUM_JSONRPC_WS_URL:
            _default: ENC[AES256_GCM,data:Lfib9uOw1+M7v/1OG7w0FjoZDRX9BwE=,iv:kRUXdJz2WtYLbM6LXovAADeQ84HsXJ9zPGh2gdoepfQ=,tag:ft0oQiJob7Q2I79CKRTy1A==,type:str]
scVerifier:
    environment:
        SMART_CONTRACT_VERIFIER__SOLIDITY__FETCHER__S3__ACCESS_KEY:
            _default: ENC[AES256_GCM,data:WcboKrQ0ffyMGvR//cWuCT7sz+06Rvc3,iv:ceUD/0rajquxo3E1VX73rzuTXg+YSd9fadDSss4/F2M=,tag:zw+ZVcKdZ2QxOQ4RDpiDhg==,type:str]
        SMART_CONTRACT_VERIFIER__SOLIDITY__FETCHER__S3__SECRET_KEY:
            _default: ENC[AES256_GCM,data:0Q4fPSKx3wu1jRW4a1TKGwdcuRG3iustHqoQRnzHZKBcXonHoa0qjw==,iv:GzYkKZ0RCpyMINHZSPiG7yT384J0wMrnTFYMnOy9EYU=,tag:IX/JNcxw1R3UHlpvdihRNA==,type:str]
        SMART_CONTRACT_VERIFIER__SOLIDITY__FETCHER__S3__BUCKET:
            _default: ENC[AES256_GCM,data:p89bs0/NjUsmQ8ms/A==,iv:W/gXfPIAajBlK2KGn2NLaTyYwgQixbTtLjZKdL02ZI0=,tag:HaIqLb9suYmB5fJI1/Ghsg==,type:str]
postgres:
    environment:
        POSTGRES_PASSWORD:
            _default: ENC[AES256_GCM,data:sL3yuVfpyRw=,iv:Dx+UOVcVaPjyeXaIMMEMRJC32L50R8TPK3iwR/APmJs=,tag:DSAw2Q45skw0pvctx1gPBQ==,type:str]
        POSTGRES_DB:
            _default: ENC[AES256_GCM,data:AeTupGw/FWZTMA==,iv:hMwGd/ctSD2gzDEfQ9dNb0XjAO2IBhhV+47meWDhQio=,tag:qF169hU9fjQ5J7pjtJSgYw==,type:str]
geth:
    files:
        list:
            genesis.json: ENC[AES256_GCM,data:52IK/W78eh0vT1APmAXroNL8iHTR/1ojT7ZizAHD1Tdrcg8Gw/xdD9P9Ow2WqZEoLgkMbokOU5ESVMJTQatwSKm3lP83i0wKx7JIQ+JtxyyR3XyY3rblTY3R4v5f+ckiqRYDstzdMnt4XhOQAm6Q07JlN97spwdplNtWFPqTzIEv5/zF6AqDmUcgKT3cKqbafo5ahVOHPg/lt2LrsvuSGM/ENlq3OE6Z9JmZG7nKVrMRkqEleVcb8SLeOFRv+7rSiGhJ6Se1818I4dnWjQCx/KTLpiZJtwZmz2Vurrk2AskcN91P0SK8cDWiR2oR3OP2dke05luhB7EBHHkEXb/62FAhOk0wtBWEkVWSWDMSaPA2fhCciw3d+A/RM0iV9krzw4n4+WyPhSt43a0gVovSxRUkxfJGGqZj5GRT9j8E8bRLi9ZBdGbkGbEUmbv8cgYpMooBTj6rlzPHGP2kv7yJ4NngY6APws6NkIIK0OkHAsP1HFTF07Up5FEtFkUG9Tqr18RU62GnkWPyXvB0aFAHf60mCDkPGove4IPO74xOGUS2cMHxFR7NFo5lyzVwN1ndvkTpxh4JE2v7Nenn65etZq6vbX5O6xBrCBquM9XjZqRaolX0pdYOG8/jdrjNd2EyNimYFDjJ5VejjZV0Un/Z7vO+SHzKpiy+EaWAUNoIix7/XGk0/oL9n3B290t+9EmpqTAu/7CS5E5pq2F6wuDLqpkIZoW2Gxyg3qm7c9xPB2Wl9e6xG3Am8gsQZQ7wVSrmNIgmEFvTI2TufN/5OCxTOJhvoAkuA3EJvpWU9EsjmYAqy8uHa0gu4J+WN17yh2uMeMDKDg2vvekn+FYP0SrpFkBcQ4W2InTQF0BVmwIlrta6wBDVcKT37XxLGpV5C6W5HzMOQ/fnHnEauO4YY8HMvqtyV4wCbibbaM24/NvcYA9EeOKNmLAart4ZVK74jgZyFQVM0mTXm+uU0u8jLXuEAQt+vVSywuQr8Qa7VsWMjegW7+O5zPNJmv7AsB3eQz8kXTLGy4+BQ7PzXMnnuv1krDk70vK7e46oIj7Kmnguf+MQKHlmV+PXBbqjLeSdlfk+oUpoSCikWiPI1fBR41AY0DBgO68qb7b992ezpC25MSI69NX1/JYl/VDoO+2n6WrSUqDYHjQ7xbq+7n4QB3RiavQyASTeXNsNyxIlR+ZsZC29fZlssQKyY1653zVYwUVpBxUAuHX2ytqEMzUoodCFf3sXA4lUGJMEgq6/rsSpVwBt2xB83yWFCFQm/hJRqy3ZCmlk4DYVd/MVc/t2ODvQdg==,iv:HEVGR7XavGkCVRQs/ytln2gn5IIu4x42jeAhK8mAc00=,tag:7DcGtafYe2/qfpAUgqO3Xg==,type:str]
            init.sh: ENC[AES256_GCM,data:cjFeSh57rgxDBxEYmMTLzIze//1jpqZuD2F9GAz4bapY0ykJS5VljH6Z62wfYM80Nhvy07xkQN1nuu5UHAdissr4QSFokpKZjCzbz+venbw/ug4dL0NDE8h2X6o3ciQJPe8jC6Ei+blRqkpiXEiDh6GDhOWNpCn6gLcAJPtePg/KiS/KAFm3PnOgjf+iGacuv4J2kzALlin9D6QQYsNyYHhjTH9YrBZZguAvPKdgQGGM3OniaJxx4FcET8aMjIrzVhD4ESwm/rFpKBF11HM1JysIjKOFDS65Z1sm62gdtk6iV6pEthr3Db2XJQL/BBPeL9VHUnLsC6GgZOvxML0rJcyO9yBlhwbtR65EymkSdacB5NXVzCig8Fb2IMhAHmGyEiFnFMBqOgUPwug95VfqTCwEvaxrEbOsGk5j/8w1ZkwTVE9OqlQziCM4gBrASxTRuclCVGazU1GQ4UiJb6i0bjDOP3/78h5PpmbO8NSGvU8IJCIik8G1UIsMpAsmTD8DbUC3ui5JC1VA9v4lu0r7awPOiaW/0anZkoE2FxJK/NsnrODTLXNlYcg7/STCHHSlwoev4E0ANMidGtTv+pamH40KtMxF4PlVbRJbG+FKQMOVuO5R4MJje3EteEyU4ph6hgZD6V1rYpG8iJNkF4RrCr6ZkfUbdp9mgAgiFNtINTyt0Uc868AGUHpRyre9y4fmf88p6IcF/oO1lyF3WeQf4D9zRShbUwnrx0ryPGtgz2idVuPOOJKUGYY9sQ==,iv:c7YKsFJsuMQjBOdyrUWHBD9s7S2lzuHi96Wt+52J4kc=,tag:hR2Y6CsWqCLyQRhKJFTe8A==,type:str]
            password.txt: ""
frontend:
    environment:
        NEXT_PUBLIC_NETWORK_TOKEN_ADDRESS:
            _default: ENC[AES256_GCM,data:iDjScwB2WgiYgk0xQZRlvL7/+TcdvHfdpx361OKX+cuJaNo5Mmlge73S,iv:JI66Yl+fJC8QiRaKcLzLwYo2O+chqWGZOhmzIVF1gfM=,tag:g+6pI9D1xnoAt57DdNAJMQ==,type:str]
        NEXT_PUBLIC_AUTH0_CLIENT_ID:
            _default: ENC[AES256_GCM,data:j45ae8bg6TtnePS5BvABQRxUOwqQhHHRkldqLxBUGcc=,iv:oX+aAz+TWvyRgRnWhWDGlYVLblSl8REET3r0CCY9QUw=,tag:dZo6HxAgJPOc8EL3uuGIPw==,type:str]
stats:
    environment:
        STATS__DB_URL:
            _default: ENC[AES256_GCM,data:2bJ3ZiRPwRcM7l8ekR0g3aiFNa7LujTCsBCIdBCrb6bEFWAET40EKX8LMgC3vyzdiAM=,iv:hyf2vkUhMlCxSHvvMWfrv53KAvInuRAjO2i/wMtx9b4=,tag:18WPm0Q79dF99ltQZH5JoA==,type:str]
        STATS__BLOCKSCOUT_DB_URL:
            _default: ENC[AES256_GCM,data:LA3a1Wjw1A4HNJyniXK/eIW+imtcoHasWtczn8WpugATFmm68SgDYM47eviHIySb/AJOBFX1Gph1/cLL3CDcCw4=,iv:YUSlq0mP1TMI8Z8jwmyltUkYVYEU0i1cvk9vavIq48Y=,tag:4TM7dof1nzYvDV16aFaPwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-01-31T13:50:01Z"
    mac: ENC[AES256_GCM,data:X8ahskOGU7WgLovvSe2acqF64CxPShbXmLU6zK64PgrRONp4oLmqC0hHb0zFp2VSQl4tTyTToodUD2mYcehaWLp9Zs/Ht8ZB2F8vhig4T5piltUYRA8auTu0xK9Sfpm59pkT7WGuXjmyneKqhY0nm8612bbZGs0k23XIq6IAl5Y=,iv:0ZIid3HxG4cbr1xIMP0MnCnXUJwIK9G4dSpIH6f4Pb8=,tag:mJ7gFR6r5Xi+XwIcrNgEsw==,type:str]
    pgp:
        - created_at: "2022-09-22T09:52:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA1MXzg1c4SMLAQf/WD1CUDjWm2YTR58vg+T8WwLdFWpmLdqRlJVnKCPg0E13
            dJXaLmNf2wVLFfVJg3pVpIT9LXphER+y+85ZTm6GUA0HZz8UrklfuIL1xprptcHY
            ocLPI7Jq6zbOEfakHlQX6AdA6Nl2DxZGSb0QWjjkC5UX9PfeTYQheHToiRwWEX2A
            RrSm2yxzM6SXjUw6/895Il9lWzyJPbBp2EIeOqr2RkobPWRHJox7Sm0Mi91VXWMH
            P8lQZjMBOE9n72IYjFydMQume8ScSB7lPiZ09xwoZzuXKNsR23IG6bGyRtlRbCxd
            IcKV00fgMrHdBBsyND9MWLwgEGqxp4YZbbPOFOGNP9JcAYTNI81+c/1BA3VWtg+N
            BTEI2wP8/HXD9sfl7tVx0Lh/o48vIxe3Lu/obZaqaRn/HcYgXTqvUezEkna5gxs9
            n+sKHNBJnKLcNrF6WRahhOYApGff/aabgxlG1Ec=
            =m714
            -----END PGP MESSAGE-----
          fp: 99E83B7490B1A9F51781E6055317CE0D5CE1230B
    unencrypted_suffix: _unencrypted
    version: 3.7.3
