@startuml
title SDLC flow with Jira and xRay
participant ProductOwner as po
participant TeamLead as tl
participant DevTeam as dt
participant Jira as j
participant QATeam as qa
participant Infra as inf

autonumber "<b>[000]"
po -> j : Create an <font color=violet>Epic</font> that describes a new service or feature
po -> j : Create software requirements for <font color=violet>Epic</font> as <font color=green>Stories</font>
qa -> j : Create <font color=grey>Test Plan</font> with description and scope based on <font color=green>Stories</font>
tl -> j : Create <font color=blue>Tasks</font> for <font color=green>Stories</font>
tl -> j : Pull some previous release\n<font color=red>Bugs</font> for a planned <b>[ fixVersion ]</b>
qa -> j : Create new <font color=red>Tests</font> that cover <font color=blue>Tasks</font> or reuse old <font color=red>Test Sets</font>
po -> j : Check preliminary traceability/coverage report
po -> j : Preliminary estimation with all teams in story points
po -> j : Bulk change all scoped entities and set <b>[ fixVersion ]</b>
po -> j : Start the sprint
qa -> j : Create <font color=aqua>Execution plan</font> for a \n<b>[ fixVersion ]</b>\n<b>[ environment ]</b>
loop 1000 times
    dt -> dt : Work on some <font color=blue>Tasks</font>
    tl -> j : Tag a feature/product in multiple repos with <b>[ RC-XX ]</b>
    dt -> j : Bulk change status to <b>[ QA ]</b>
    qa -> qa : Execute <font color=red>Tests</font>\nfor <b>[ RC-XX ]</b> on local or tesnet <b>[ environment ]</b>
    qa -> qa : Post <font color=red>Bugs</font> with \n<b>[ affectedVersion ]</b>\n<b>[ environment ]</b>
    qa -> j : Bulk change status to <b>[ In Progress ]</b>
    po -> j : Reestimate <font color=blue>Tasks</font>, <font color=red>Bugs</font> and <font color=red>Tests</font> with all teams
end
qa -> j : Finish <font color=aqua>Execution plan</font>
qa -> j : Create <font color=aqua>Execution plan</font> report/dashboard/traceability for a <b>[ fixVersion ]</b>
po -> j : Check <font color=aqua>Execution plan</font> report/dashboard/traceability for a <b>[ fixVersion ]</b>
po -> j : Change release scope if needed, set <b>[ fixVersion + 1 ]</b>\nto some <font color=blue>Tasks</font>, <font color=red>Bugs</font> and <font color=red>Tests</font>
po -> inf : Create testnet deployment ticket for <b>[ RC-XX ]</b>
po -> j : Bulk change all scoped entities to <b>[ QA ]</b>
qa -> j : Create <font color=aqua>Execution plan</font> for a \n<b>[ fixVersion ]</b>\n<b>[ environment ]</b>
j -> j : Repeat steps <b>[ 012 - 018 ]</b>
qa -> j : Finish <font color=aqua>Execution plan</font>
qa -> j : Create <font color=aqua>Execution plan</font> report/dashboard/traceability for a <b>[ fixVersion ]</b>

po -> j : Check <font color=aqua>Execution plan</font> report/dashboard/traceability for a <b>[ fixVersion ]</b>
po -> j : Change release scope if needed, set <b>[ fixVersion + 1 ]</b>\nto some <font color=blue>Tasks</font>, <font color=red>Bugs</font> and <font color=red>Tests</font>
po -> inf : Create <b>mainnet</b> deployment ticket for <b>[ RELEASE-XX ]</b>
po -> j : Bulk change all scoped entities to <b>[ QA ]</b>
qa -> j : Create <font color=aqua>Execution plan</font> for a \n<b>[ fixVersion ]</b>\n<b>[ environment ]</b>
j -> j : Repeat steps <b>[ 012 - 018 ]</b>
qa -> j : Finish <font color=aqua>Execution plan</font>
qa -> j : Create <font color=aqua>Execution plan</font> report/dashboard/traceability for a <b>[ fixVersion ]</b>
po -> j : Check <font color=aqua>Execution plan</font> report/dashboard/traceability for a <b>[ fixVersion ]</b>
po -> j : Change release scope if needed, set <b>[ fixVersion + 1 ]</b>\nto some <font color=blue>Tasks</font>, <font color=red>Bugs</font> and <font color=red>Tests</font>
po -> j : Bulk change all scoped entities to <b>[ Done ]</b>
po -> j : Finish sprint
@enduml