{{- if .Values.scVerifier.enabled }}
{{- if .Values.scVerifier.hpa.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-sc-verifier
spec:
  maxReplicas: {{ .Values.scVerifier.hpa.maxReplicas }}
  minReplicas: {{ .Values.scVerifier.hpa.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-sc-verifier
  targetCPUUtilizationPercentage: {{ .Values.scVerifier.hpa.cpuTarget }}
{{- end }}
{{- end }}
