{{- if .Values.geth.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: geth-cm
data:
  {{- range $key, $value := .Values.geth.files }}
  {{ $key }}: {{ toYaml $value | indent 2 }}
  {{- end }}
{{- end }}
