{{- if .Values.geth.enabled }}
{{- if .Values.geth.jwt.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: jwt
data:
  jwtsecret: {{ .Values.geth.jwt.token | b64enc | quote }}
{{- end }}
{{- end }}
