{{- if .Values.tokenInfoExtractor.enabled }}
{{- if .Values.tokenInfoExtractor.files.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: token-info-extractor-cm
data:
  {{- range $key, $value := .Values.tokenInfoExtractor.files.list }}
  {{ $key }}: {{ toYaml $value | indent 2 }}
  {{- end }}
{{- end }}
{{- end }}
