{{- if .Values.tokenInfoExtractor.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-token-info-extractor
spec:
  schedule: {{ pluck $.Values.global.env .Values.tokenInfoExtractor.schedule | first | default .Values.tokenInfoExtractor.schedule._default | quote }}
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      backoffLimit: 6
      completions: 1
      parallelism: 1
      template:
        spec:
          restartPolicy: Never
          imagePullSecrets:
            - name: regcred
          containers:
            - name: {{ .Release.Name }}-token-info-extractor
              image: {{ pluck $.Values.global.env .Values.tokenInfoExtractor.image | first | default .Values.tokenInfoExtractor.image._default | quote }}
              resources:
              {{- with .Values.tokenInfoExtractor.resources }}
                limits:
                  memory: {{ pluck $.Values.global.env .limits.memory | first | default .limits.memory._default | quote }}
                  cpu: {{ pluck $.Values.global.env .limits.cpu | first | default .limits.cpu._default | quote }}
                requests:
                  memory: {{ pluck $.Values.global.env .requests.memory | first | default .requests.memory._default | quote }}
                  cpu: {{ pluck $.Values.global.env .requests.cpu | first | default .requests.cpu._default | quote }}
              {{- end }}
              imagePullPolicy: Always
              env:
{{- include "tokenInfoExtractor_env" . | indent 16 }}
              {{- if .Values.tokenInfoExtractor.files.enabled }}
              volumeMounts:
                {{- range $key, $value := .Values.tokenInfoExtractor.files.list }}
                - mountPath: {{ $.Values.tokenInfoExtractor.files.mountPath }}/{{ $key }}
                  name: token-info-extractor-cm
                  subPath: {{ $key }}
                {{- end }}
              {{- end }}
          {{- if .Values.tokenInfoExtractor.files.enabled }}
          volumes:
            - configMap:
                name: token-info-extractor-cm
                defaultMode: 0777
              name: token-info-extractor-cm
          {{- end }}
          {{- if .Values.tokenInfoExtractor.nodeSelector.enabled }}
          nodeSelector:
          {{- pluck $.Values.global.env .Values.tokenInfoExtractor.nodeSelector.labels | first | default .Values.tokenInfoExtractor.nodeSelector.labels._default | toYaml | nindent 8 }}
          {{- end }}
---
{{- end}}
