name: E2E Env Matrix (API) AutoScout

on:
  push:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  autoscout-api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Call E2E Env Matrix (API) Top 16
        uses: ./.github/workflows/e2e-env-matrix-api-top-16.yml
        with:
          urls: ${{ fromJson(["https://parthenon.athenescan.io", "https://hyperliquid.cloud.blockscout.com"]) }}