name: E2E Env Matrix (API) AutoScout

on:
  push:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  tests:
    uses: blockscout/blockscout-ci-cd/.github/workflows/e2e_matrix_api.yaml@master
    with:
      urls: '["https://parthenon.athenescan.io", "https://hyperliquid.cloud.blockscout.com"]'