name: OpenAPI Diff Workflow

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'The repository URL to clone (default: blockscout/blockscout-api-v2-swagger)'
        required: false
        default: 'blockscout/blockscout-api-v2-swagger'
      head-branch:
        description: 'The head branch to compare (default: current branch)'
        required: false
        default: ''
      base-branch:
        description: 'The base branch to compare against (default: main)'
        required: false
        default: 'main'
      head-spec-path:
        description: 'Path to the OpenAPI spec in the head branch'
        required: true
        default: 'swagger.yaml'
      base-spec-path:
        description: 'Path to the OpenAPI spec in the base branch'
        required: true
        default: 'swagger.yaml'

jobs:
  compare-openapi:
    runs-on: ubuntu-latest
    steps:
      - name: Check out head branch
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repository }}
          ref: ${{ github.event.inputs.head-branch || github.ref }}
          path: head

      - name: Check out base branch
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repository }}
          ref: ${{ github.event.inputs.base-branch }}
          path: base

      - name: Run OpenAPI Diff using Docker
        run: |
          docker run --rm -v $(pwd)/head:/head:ro -v $(pwd)/base:/base:ro \
            openapitools/openapi-diff \
            /head/${{ github.event.inputs.head-spec-path }} \
            /base/${{ github.event.inputs.base-spec-path }}