name: OpenAPI Diff Workflow

on:
  workflow_dispatch:
    inputs:
      head-branch:
        description: 'The head branch to compare (default: current branch)'
        required: false
        default: ''
      base-branch:
        description: 'The base branch to compare against (default: master)'
        required: false
        default: 'master'
      head-spec-path:
        description: 'Path to the OpenAPI spec in the head branch'
        required: true
        default: 'spec/openapi.yaml'
      base-spec-path:
        description: 'Path to the OpenAPI spec in the base branch'
        required: true
        default: 'spec/openapi.yaml'

jobs:
  compare-openapi:
    runs-on: ubuntu-latest
    steps:
      - name: Check out head branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.head-branch || github.ref }}
          path: head

      - name: Check out base branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.base-branch }}
          path: base

      - name: Run OpenAPI Diff
        uses: mvegter/openapi-diff-action@v0.23.5
        with:
          head-spec: head/${{ github.event.inputs.head-spec-path }}
          base-spec: base/${{ github.event.inputs.base-spec-path }}