kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "http-metrics"
spec:
  replicas: {{ .Values.replicas.sc_verifier }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      # serviceAccountName: vault-auth
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image }}
          resources:
          {{- with .Values.resources }}
            limits:
              memory: {{ pluck $.Values.global.env .limits.memory | first | default .limits.memory._default | quote }}
              cpu: {{ pluck $.Values.global.env .limits.cpu | first | default .limits.cpu._default | quote }}
            requests:
              memory: {{ pluck $.Values.global.env .requests.memory | first | default .requests.memory._default | quote }}
              cpu: {{ pluck $.Values.global.env .requests.cpu | first | default .requests.cpu._default | quote }}
          {{- end }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.docker.targetPort }}
            - containerPort: {{ .Values.docker.metricsPort }}
              name: http-metrics
          env:
{{- include "app_env" . | indent 10 }}
          # volumeMounts:
          #   - name: {{ .Release.Name }}-logs
          #     mountPath: /usr/local/gkretail/sm-web-server/log
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.docker.port }}
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.docker.port }}
              scheme: HTTP
            initialDelaySeconds: 100
            periodSeconds: 100
      # volumes:
      #   - name: {{ .Release.Name }}-logs
      #     emptyDir: { }
      #   - name: config
      #     configMap:
      #       name: {{ .Release.Name }}-promtail-configmap
      restartPolicy: Always
---
