{{- if .Values.adminRs.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: admin-rs-svc
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
  #   service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
  #   service.beta.kubernetes.io/aws-load-balancer-type: external
  labels:
    app: {{ .Release.Name }}-admin-rs
spec:
  type: {{ .Values.adminRs.service.type}}
  ports:
    - port: {{ .Values.adminRs.docker.port }}
      targetPort: {{ .Values.adminRs.docker.targetPort }}
      protocol: TCP
      name: web
    # - port: {{ .Values.adminRs.docker.metricsPort }}
    #   targetPort: {{ .Values.adminRs.docker.metricsPort }}
    #   protocol: TCP
    #   name: http-metrics
  selector:
    app: {{ .Release.Name }}-admin-rs
{{- end }}
---
